# RRNN - keras

### librerias

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### importar dataset

In [2]:
dataset = pd.read_csv('Iris2.csv')

### seleccion de variables

In [3]:
X = dataset.iloc[:,1:5].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = dataset.iloc[:,5].values
#y = np.array(y,dtype=np.float32)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

### codificacion datos categoricos

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1=LabelEncoder()
X[:,1]=labelencoder_X_1.fit_transform(X[:,1])
X

labelencoder_X_2=LabelEncoder()
X[:,2]=labelencoder_X_2.fit_transform(X[:,2])
X

#### creacion de las variables dummies

cuando se cambia una variable categorica en una nueva clase 

transformer = ColumnTransformer(
    transformers=[
        ("OneHot",        # Just a name
         OneHotEncoder(), # The transformer class
         [1]              # The column(s) to be applied on.
         )
    ],
    remainder='passthrough' # donot apply anything to the remaining columns
)
X = transformer.fit_transform(X.tolist())
X = np.array(X,dtype=np.float32)
X.dtype

### Division de los datos de prueb a y entrenamiento

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

### Ajustar las escalas

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# Creacion de la Red Neuronal

### importacion de las librerias

In [9]:
import keras
from keras.models import Sequential #arquitectura
from keras.layers import Dense      #capa de la red  
from keras.layers import Flatten

### inicialziacion de la red neuronal

In [10]:
red = Sequential()

### capa de entrada

tenemos 11 variables de entrada y una de salida (si,no)
ademas de construiran 2 capas ocultas de 12 neuronas cada una


In [11]:
capa_1=Dense(1,input_dim=4,use_bias=1,activation='sigmoid')
capa_2=Dense(4,use_bias=1,activation='sigmoid')
capa_3=Dense(1,use_bias=1,activation='sigmoid')

In [12]:
red.add(capa_1)
#red.add(capa_2)
#red.add(capa_3)

### activacion

In [13]:
red.compile(
    optimizer='adam',
    loss='binary_crossentropy', #binary_crossentropy
    metrics=['accuracy']
)

In [14]:
np.shape(X_train)

(80, 4)

### entrenamiento

In [15]:
%%timeit 
red.fit(X_train,
        y_train,
        epochs=10,
        batch_size=1
       )

Epoch 1/10
80/80 [==============================] - 0s 791us/step - loss: 1.6639 - accuracy: 0.0250
Epoch 2/10
80/80 [==============================] - 0s 1ms/step - loss: 1.4992 - accuracy: 0.0625
Epoch 3/10
80/80 [==============================] - 0s 874us/step - loss: 1.3472 - accuracy: 0.0750
Epoch 4/10
80/80 [==============================] - 0s 873us/step - loss: 1.2088 - accuracy: 0.2125
Epoch 5/10
80/80 [==============================] - 0s 791us/step - loss: 1.0835 - accuracy: 0.3125
Epoch 6/10
80/80 [==============================] - 0s 874us/step - loss: 0.9710 - accuracy: 0.3500
Epoch 7/10
80/80 [==============================] - 0s 1ms/step - loss: 0.8712 - accuracy: 0.3875
Epoch 8/10
80/80 [==============================] - 0s 874us/step - loss: 0.7827 - accuracy: 0.4625
Epoch 9/10
80/80 [==============================] - 0s 871us/step - loss: 0.7050 - accuracy: 0.5125
Epoch 10/10
80/80 [==============================] - 0s 989us/step - loss: 0.6364 - accuracy: 0.6375
Epo

### predicción

In [16]:
y_pred=red.predict(X_test)
y_pred

array([[0.01501057],
       [0.99944305],
       [0.0042941 ],
       [0.9924592 ],
       [0.99890554],
       [0.8803444 ],
       [0.00961566],
       [0.9967769 ],
       [0.9994749 ],
       [0.97802556],
       [0.992832  ],
       [0.9907944 ],
       [0.9975967 ],
       [0.00147876],
       [0.00710458],
       [0.00936404],
       [0.00102875],
       [0.0068309 ],
       [0.00376186],
       [0.00446403]], dtype=float32)

In [17]:
y_pred = np.round(y_pred)
y_pred

array([[0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

### comparacion de resultados

In [18]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test,y_pred)

In [19]:
cm

array([[10,  0],
       [ 0, 10]], dtype=int64)

array([[1506,   89],
       [ 189,  216]], dtype=int64)

In [20]:
scores = red.evaluate(X_train, y_train)
print("\n%s: %.2f%%" % (red.metrics_names[1], scores[1]*100))

3/3 [==============================] - 0s 0s/step - loss: 0.0149 - accuracy: 1.0000

accuracy: 100.00%


In [21]:
scores = red.evaluate(X_test, y_test)
print("\n%s: %.2f%%" % (red.metrics_names[1], scores[1]*100))

1/1 [==============================] - 0s 31ms/step - loss: 0.0122 - accuracy: 1.0000

accuracy: 100.00%


In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        10
         1.0       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

